import Head from 'next/head'
import { FaSearch, FaRegBell, FaChevronDown } from "react-icons/fa"

import Profil from '@/component/home/profil'
import useProfil from '@/hook/useProfil'
import { NextPageContext } from 'next'
import { getSession } from 'next-auth/react'
import { map } from "lodash"
import Thumbnail from '@/component/home/thumbnail'
import Movie from '@/component/home/movie'
import useMovies from '@/hook/useMovies'
import useFavorites from '@/hook/useFavorites'
import InfoModel from '@/component/home/infomodel'
import useMovieRandom from '@/hook/useMovieRandom'
import Nav from '@/component/home/nav'
import Loading from '@/component/loading/loading'

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false
      }
    }
  }

  return {props: {}}
}

export default function Home() {
  // useState 
  const {isLoading: loadingThumbnail} = useMovieRandom();

  const {data: movies, isLoading: loadingMovies} = useMovies()

  const {data: favorites} = useFavorites();

  const {isLoading} = useProfil()  

  if (isLoading && loadingMovies && loadingThumbnail) {
    return (
      <Loading />
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='author' content='Udin' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-black w-full h-full block pb-40'>
        {/* header */}
        <Nav />

        {/* Body */}
        <body>
          
          <Thumbnail />
          <article className='mx-14 mt-4'>
            {/* Trending section */}
            <h1 className="text-white font-serif text-2xl">Trending Now</h1>
            <section className='grid grid-cols-3 mt-4 gap-x-3'>
            {map(movies, (value: any, index: any) => (
              <Movie key={index} data={value} />
            ))}
            </section>

            <h1 className="text-white font-serif text-2xl mt-4">Favorite</h1>
            <section className='grid grid-cols-3 mt-4 gap-x-3'>
              {map(favorites, (value: any, index: any) => (
                <Movie key={index} data={value} />
              ))}

            </section>

            <section>
              <InfoModel />
            </section>
          </article>
        </body>
        
      </main>
    </>
  )
}
